// <auto-generated />
using LabGD2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LabGD2.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20240805115833_intial")]
    partial class intial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LabGD2.Data.Entities.NhaSanXuat", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NhaSanXuats");

                    b.HasData(
                        new
                        {
                            Id = "Id1",
                            DiaChi = "Hà Nội",
                            Ten = "FPT"
                        },
                        new
                        {
                            Id = "Id2",
                            DiaChi = "Hà Nội",
                            Ten = "Viettel"
                        },
                        new
                        {
                            Id = "Id3",
                            DiaChi = "Hà Nội",
                            Ten = "Mobiphone"
                        });
                });

            modelBuilder.Entity("LabGD2.Data.Entities.SanPham", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdNhaSanXuat")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdNhaSanXuat");

                    b.ToTable("SanPhams");
                });

            modelBuilder.Entity("LabGD2.Data.Entities.SanPham", b =>
                {
                    b.HasOne("LabGD2.Data.Entities.NhaSanXuat", "NhaSanXuat")
                        .WithMany("SanPham")
                        .HasForeignKey("IdNhaSanXuat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhaSanXuat");
                });

            modelBuilder.Entity("LabGD2.Data.Entities.NhaSanXuat", b =>
                {
                    b.Navigation("SanPham");
                });
#pragma warning restore 612, 618
        }
    }
}
